### ISSUE TITLE
Description or Summary

### ISSUE THREAD

**Issue by ISeeTWizard** [Accudio/monolith-koken#2]
Hi

is there a way to get a summary or description of an album displayed?

Thanks already in advance and great work 👍

**Comment by Accudio** [comment]
If an Album has a description it should be displayed above the contents, and under the title and image when in 'Albums' or in a Set. Let me know if you have any issues with this!

**Comment by ISeeTWizard** [comment]
It was my fault as for my old theme I had to put all under Summary and I forgot that ;(
