### ISSUE TITLE
Cropped images

### ISSUE THREAD

**Issue by ISeeTWizard** [Accudio/monolith-koken#3]
Hi

Is there a way to prevent cropped images?

**Comment by Accudio** [comment]
Hi,

Currently images are fixed to an aspect ratio of 5:3 to provide consistent sizing across the theme. If there was an option to disable the fixed aspect ratio, would you want this to be a site-wide setting or per-template?

Edit: Likewise, it would not be difficult for a way to customise the aspect ratio used to be implemented, however this would face the same question.

**Comment by ISeeTWizard** [comment]
I think a this would be a great template setting so instead of cropping it goes transparent or so? Or an option like 3:4 2:3 16:9 or so... I know it's not easy to decide. 
For the album it's ok, there I can choose an image which is cropped ok but the listing with the photos is not top like it is. 
Like with Regale 2 an option to use randomed sized image is also an idea...

**Comment by Accudio** [comment]
I will look into this as a possibility for the next major release of the theme. It is designed for strict row/column layouts so a uniform aspect ratio change or crop disable seems reasonable however I suspect a random sized image would be something I would not consider implementing myself certainly in the near future. 

Pull Requests for new features are welcome however, if someone else wanted to develop this I suggest the best way to do so would be through a "Template Style" setting on particular template pages. This could allow future alternate styles such as masonry or row based too.
